pluginManagement {
    repositories {
        maven { url "https://maven.resourcefulbees.com/repository/maven-public/" }
        gradlePluginPortal()
    }
}

plugins {
    id 'com.teamresourceful.resourcefulsettings' version '0.0.13'
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
