package com.dungeonderps.resourcefulbees.config;

import net.minecraftforge.common.ForgeConfigSpec;

public class ResourcefulBeesConfig {

    public static ForgeConfigSpec.BooleanValue GENERATE_DEFAULTS;
    public static ForgeConfigSpec.BooleanValue ENABLE_EASTER_EGG_BEES;
    public static ForgeConfigSpec.BooleanValue CENTRIFUGE_RECIPES;
    public static ForgeConfigSpec.BooleanValue HONEYCOMB_BLOCK_RECIPES;
    public static ForgeConfigSpec.DoubleValue HIVE_OUTPUT_MODIFIER;
    public static ForgeConfigSpec.DoubleValue CENTRIFUGE_RECIPE_MAIN;
    public static ForgeConfigSpec.DoubleValue CENTRIFUGE_RECIPE_SECONDARY;
    public static ForgeConfigSpec.DoubleValue CENTRIFUGE_RECIPE_HONEYBOTTLE;
    public static ForgeConfigSpec.IntValue CENTRIFUGE_RECIPE_TIME;
    public static ForgeConfigSpec.IntValue HIVE_MAX_BEES;

    public static class CommonConfig {

        public static ForgeConfigSpec COMMON_CONFIG;

        static {
            ForgeConfigSpec.Builder COMMON_BUILDER = new ForgeConfigSpec.Builder();

            COMMON_BUILDER.push("General Options");
                GENERATE_DEFAULTS = COMMON_BUILDER.comment("Set to true if you want our default bees to populate the bees folder [true/false]")
                        .define("generateDefaults",true);
                ENABLE_EASTER_EGG_BEES = COMMON_BUILDER.comment("Set to true if you want easter egg bees to generate [true/false]")
                        .define("enableEasterEggBees", true);
            COMMON_BUILDER.pop();

            COMMON_BUILDER.push("Recipe Options");
                CENTRIFUGE_RECIPES = COMMON_BUILDER.comment("Set to false if you don't want the centrifuge recipes to be auto generated [true/false]")
                        .define("centrifugeRecipes", true);
                HONEYCOMB_BLOCK_RECIPES = COMMON_BUILDER.comment("Set to false if you don't want the honeycomb block recipes to be auto generated [true/false]")
                        .define("honeycombBlockRecipes", true);
            COMMON_BUILDER.pop();

            COMMON_BUILDER.push("Centrifuge Options");
                CENTRIFUGE_RECIPE_MAIN = COMMON_BUILDER.comment("Main material chance for generated centrifuge recipes","This does not affect recipes that are not auto generated by us.")
                        .defineInRange("centrifugeRecipeMainChance", 1.0,0.0,1.0);
                CENTRIFUGE_RECIPE_SECONDARY = COMMON_BUILDER.comment("Secondary material(beeswax) chance for generated centrifuge recipes","This does not affect recipes that are not auto generated by us.")
                        .defineInRange("centrifugeRecipeSecondaryChance", 0.2,0.0,1.0);
                CENTRIFUGE_RECIPE_HONEYBOTTLE = COMMON_BUILDER.comment("Honey bottle chance for generated centrifuge recipes","This does not affect recipes that are not auto generated by us.")
                        .defineInRange("centrifugeRecipeBottleChance", 0.25,0.0,1.0);
                CENTRIFUGE_RECIPE_TIME = COMMON_BUILDER.comment("Honey bottle chance for generated centrifuge recipes","This does not affect recipes that are not auto generated by us.","Time is in seconds.")
                        .defineInRange("centrifugeRecipeTime", 10,1,60);
            COMMON_BUILDER.pop();

            COMMON_BUILDER.push("Beehive Options");
                HIVE_OUTPUT_MODIFIER = COMMON_BUILDER.comment("Output modifier for the hives when ready to be harvested")
                        .defineInRange("hiveOutputModifier", 5.0,1.0,10.0);
                HIVE_MAX_BEES = COMMON_BUILDER.comment("Maximum amount of bees in the hive at any given time")
                        .defineInRange("hiveMaxBees", 4, 0, 16);
            COMMON_BUILDER.pop();

            COMMON_CONFIG = COMMON_BUILDER.build();
        }
    }
}
