package com.teamresourceful.resourcefulbees.common.utils.color;

import com.teamresourceful.resourcefulbees.common.lib.constants.ModConstants;

@SuppressWarnings("unused")
public final class ConstantColors {

    private ConstantColors() {
        throw new IllegalStateException(ModConstants.UTILITY_CLASS);
    }

    //You can add colors here when needed.

    //region CSS Colors - Found at https://github.com/bahamas10/css-color-names/blob/master/css-color-names.json in case if it updates.
    public static final Color aliceblue = Color.createNamedColor("aliceblue",0xf0f8ff);
    public static final Color antiquewhite = Color.createNamedColor("antiquewhite",0xfaebd7);
    public static final Color aqua = Color.createNamedColor("aqua",0x00ffff);
    public static final Color aquamarine = Color.createNamedColor("aquamarine",0x7fffd4);
    public static final Color azure = Color.createNamedColor("azure",0xf0ffff);
    public static final Color beige = Color.createNamedColor("beige",0xf5f5dc);
    public static final Color bisque = Color.createNamedColor("bisque",0xffe4c4);
    public static final Color black = Color.createNamedColor("black",0x000000);
    public static final Color blanchedalmond = Color.createNamedColor("blanchedalmond",0xffebcd);
    public static final Color blue = Color.createNamedColor("blue",0x0000ff);
    public static final Color blueviolet = Color.createNamedColor("blueviolet",0x8a2be2);
    public static final Color brown = Color.createNamedColor("brown",0xa52a2a);
    public static final Color burlywood = Color.createNamedColor("burlywood",0xdeb887);
    public static final Color cadetblue = Color.createNamedColor("cadetblue",0x5f9ea0);
    public static final Color chartreuse = Color.createNamedColor("chartreuse",0x7fff00);
    public static final Color chocolate = Color.createNamedColor("chocolate",0xd2691e);
    public static final Color coral = Color.createNamedColor("coral",0xff7f50);
    public static final Color cornflowerblue = Color.createNamedColor("cornflowerblue",0x6495ed);
    public static final Color cornsilk = Color.createNamedColor("cornsilk",0xfff8dc);
    public static final Color crimson = Color.createNamedColor("crimson",0xdc143c);
    public static final Color cyan = Color.createNamedColor("cyan",0x00ffff);
    public static final Color darkblue = Color.createNamedColor("darkblue",0x00008b);
    public static final Color darkcyan = Color.createNamedColor("darkcyan",0x008b8b);
    public static final Color darkgoldenrod = Color.createNamedColor("darkgoldenrod",0xb8860b);
    public static final Color darkgray = Color.createNamedColor("darkgray",0xa9a9a9);
    public static final Color darkgreen = Color.createNamedColor("darkgreen",0x006400);
    public static final Color darkgrey = Color.createNamedColor("darkgrey",0xa9a9a9);
    public static final Color darkkhaki = Color.createNamedColor("darkkhaki",0xbdb76b);
    public static final Color darkmagenta = Color.createNamedColor("darkmagenta",0x8b008b);
    public static final Color darkolivegreen = Color.createNamedColor("darkolivegreen",0x556b2f);
    public static final Color darkorange = Color.createNamedColor("darkorange",0xff8c00);
    public static final Color darkorchid = Color.createNamedColor("darkorchid",0x9932cc);
    public static final Color darkred = Color.createNamedColor("darkred",0x8b0000);
    public static final Color darksalmon = Color.createNamedColor("darksalmon",0xe9967a);
    public static final Color darkseagreen = Color.createNamedColor("darkseagreen",0x8fbc8f);
    public static final Color darkslateblue = Color.createNamedColor("darkslateblue",0x483d8b);
    public static final Color darkslategray = Color.createNamedColor("darkslategray",0x2f4f4f);
    public static final Color darkslategrey = Color.createNamedColor("darkslategrey",0x2f4f4f);
    public static final Color darkturquoise = Color.createNamedColor("darkturquoise",0x00ced1);
    public static final Color darkviolet = Color.createNamedColor("darkviolet",0x9400d3);
    public static final Color deeppink = Color.createNamedColor("deeppink",0xff1493);
    public static final Color deepskyblue = Color.createNamedColor("deepskyblue",0x00bfff);
    public static final Color dimgray = Color.createNamedColor("dimgray",0x696969);
    public static final Color dimgrey = Color.createNamedColor("dimgrey",0x696969);
    public static final Color dodgerblue = Color.createNamedColor("dodgerblue",0x1e90ff);
    public static final Color firebrick = Color.createNamedColor("firebrick",0xb22222);
    public static final Color floralwhite = Color.createNamedColor("floralwhite",0xfffaf0);
    public static final Color forestgreen = Color.createNamedColor("forestgreen",0x228b22);
    public static final Color fuchsia = Color.createNamedColor("fuchsia",0xff00ff);
    public static final Color gainsboro = Color.createNamedColor("gainsboro",0xdcdcdc);
    public static final Color ghostwhite = Color.createNamedColor("ghostwhite",0xf8f8ff);
    public static final Color goldenrod = Color.createNamedColor("goldenrod",0xdaa520);
    public static final Color gold = Color.createNamedColor("gold",0xffd700);
    public static final Color gray = Color.createNamedColor("gray",0x808080);
    public static final Color green = Color.createNamedColor("green",0x008000);
    public static final Color greenyellow = Color.createNamedColor("greenyellow",0xadff2f);
    public static final Color grey = Color.createNamedColor("grey",0x808080);
    public static final Color honeydew = Color.createNamedColor("honeydew",0xf0fff0);
    public static final Color hotpink = Color.createNamedColor("hotpink",0xff69b4);
    public static final Color indianred = Color.createNamedColor("indianred",0xcd5c5c);
    public static final Color indigo = Color.createNamedColor("indigo",0x4b0082);
    public static final Color ivory = Color.createNamedColor("ivory",0xfffff0);
    public static final Color khaki = Color.createNamedColor("khaki",0xf0e68c);
    public static final Color lavenderblush = Color.createNamedColor("lavenderblush",0xfff0f5);
    public static final Color lavender = Color.createNamedColor("lavender",0xe6e6fa);
    public static final Color lawngreen = Color.createNamedColor("lawngreen",0x7cfc00);
    public static final Color lemonchiffon = Color.createNamedColor("lemonchiffon",0xfffacd);
    public static final Color lightblue = Color.createNamedColor("lightblue",0xadd8e6);
    public static final Color lightcoral = Color.createNamedColor("lightcoral",0xf08080);
    public static final Color lightcyan = Color.createNamedColor("lightcyan",0xe0ffff);
    public static final Color lightgoldenrodyellow = Color.createNamedColor("lightgoldenrodyellow",0xfafad2);
    public static final Color lightgray = Color.createNamedColor("lightgray",0xd3d3d3);
    public static final Color lightgreen = Color.createNamedColor("lightgreen",0x90ee90);
    public static final Color lightgrey = Color.createNamedColor("lightgrey",0xd3d3d3);
    public static final Color lightpink = Color.createNamedColor("lightpink",0xffb6c1);
    public static final Color lightsalmon = Color.createNamedColor("lightsalmon",0xffa07a);
    public static final Color lightseagreen = Color.createNamedColor("lightseagreen",0x20b2aa);
    public static final Color lightskyblue = Color.createNamedColor("lightskyblue",0x87cefa);
    public static final Color lightslategray = Color.createNamedColor("lightslategray",0x778899);
    public static final Color lightslategrey = Color.createNamedColor("lightslategrey",0x778899);
    public static final Color lightsteelblue = Color.createNamedColor("lightsteelblue",0xb0c4de);
    public static final Color lightyellow = Color.createNamedColor("lightyellow",0xffffe0);
    public static final Color lime = Color.createNamedColor("lime",0x00ff00);
    public static final Color limegreen = Color.createNamedColor("limegreen",0x32cd32);
    public static final Color linen = Color.createNamedColor("linen",0xfaf0e6);
    public static final Color magenta = Color.createNamedColor("magenta",0xff00ff);
    public static final Color maroon = Color.createNamedColor("maroon",0x800000);
    public static final Color mediumaquamarine = Color.createNamedColor("mediumaquamarine",0x66cdaa);
    public static final Color mediumblue = Color.createNamedColor("mediumblue",0x0000cd);
    public static final Color mediumorchid = Color.createNamedColor("mediumorchid",0xba55d3);
    public static final Color mediumpurple = Color.createNamedColor("mediumpurple",0x9370db);
    public static final Color mediumseagreen = Color.createNamedColor("mediumseagreen",0x3cb371);
    public static final Color mediumslateblue = Color.createNamedColor("mediumslateblue",0x7b68ee);
    public static final Color mediumspringgreen = Color.createNamedColor("mediumspringgreen",0x00fa9a);
    public static final Color mediumturquoise = Color.createNamedColor("mediumturquoise",0x48d1cc);
    public static final Color mediumvioletred = Color.createNamedColor("mediumvioletred",0xc71585);
    public static final Color midnightblue = Color.createNamedColor("midnightblue",0x191970);
    public static final Color mintcream = Color.createNamedColor("mintcream",0xf5fffa);
    public static final Color mistyrose = Color.createNamedColor("mistyrose",0xffe4e1);
    public static final Color moccasin = Color.createNamedColor("moccasin",0xffe4b5);
    public static final Color navajowhite = Color.createNamedColor("navajowhite",0xffdead);
    public static final Color navy = Color.createNamedColor("navy",0x000080);
    public static final Color oldlace = Color.createNamedColor("oldlace",0xfdf5e6);
    public static final Color olive = Color.createNamedColor("olive",0x808000);
    public static final Color olivedrab = Color.createNamedColor("olivedrab",0x6b8e23);
    public static final Color orange = Color.createNamedColor("orange",0xffa500);
    public static final Color orangered = Color.createNamedColor("orangered",0xff4500);
    public static final Color orchid = Color.createNamedColor("orchid",0xda70d6);
    public static final Color palegoldenrod = Color.createNamedColor("palegoldenrod",0xeee8aa);
    public static final Color palegreen = Color.createNamedColor("palegreen",0x98fb98);
    public static final Color paleturquoise = Color.createNamedColor("paleturquoise",0xafeeee);
    public static final Color palevioletred = Color.createNamedColor("palevioletred",0xdb7093);
    public static final Color papayawhip = Color.createNamedColor("papayawhip",0xffefd5);
    public static final Color peachpuff = Color.createNamedColor("peachpuff",0xffdab9);
    public static final Color peru = Color.createNamedColor("peru",0xcd853f);
    public static final Color pink = Color.createNamedColor("pink",0xffc0cb);
    public static final Color plum = Color.createNamedColor("plum",0xdda0dd);
    public static final Color powderblue = Color.createNamedColor("powderblue",0xb0e0e6);
    public static final Color purple = Color.createNamedColor("purple",0x800080);
    public static final Color rebeccapurple = Color.createNamedColor("rebeccapurple",0x663399);
    public static final Color red = Color.createNamedColor("red",0xff0000);
    public static final Color rosybrown = Color.createNamedColor("rosybrown",0xbc8f8f);
    public static final Color royalblue = Color.createNamedColor("royalblue",0x4169e1);
    public static final Color saddlebrown = Color.createNamedColor("saddlebrown",0x8b4513);
    public static final Color salmon = Color.createNamedColor("salmon",0xfa8072);
    public static final Color sandybrown = Color.createNamedColor("sandybrown",0xf4a460);
    public static final Color seagreen = Color.createNamedColor("seagreen",0x2e8b57);
    public static final Color seashell = Color.createNamedColor("seashell",0xfff5ee);
    public static final Color sienna = Color.createNamedColor("sienna",0xa0522d);
    public static final Color silver = Color.createNamedColor("silver",0xc0c0c0);
    public static final Color skyblue = Color.createNamedColor("skyblue",0x87ceeb);
    public static final Color slateblue = Color.createNamedColor("slateblue",0x6a5acd);
    public static final Color slategray = Color.createNamedColor("slategray",0x708090);
    public static final Color slategrey = Color.createNamedColor("slategrey",0x708090);
    public static final Color snow = Color.createNamedColor("snow",0xfffafa);
    public static final Color springgreen = Color.createNamedColor("springgreen",0x00ff7f);
    public static final Color steelblue = Color.createNamedColor("steelblue",0x4682b4);
    public static final Color tan = Color.createNamedColor("tan",0xd2b48c);
    public static final Color teal = Color.createNamedColor("teal",0x008080);
    public static final Color thistle = Color.createNamedColor("thistle",0xd8bfd8);
    public static final Color tomato = Color.createNamedColor("tomato",0xff6347);
    public static final Color turquoise = Color.createNamedColor("turquoise",0x40e0d0);
    public static final Color violet = Color.createNamedColor("violet",0xee82ee);
    public static final Color wheat = Color.createNamedColor("wheat",0xf5deb3);
    public static final Color white = Color.createNamedColor("white",0xffffff);
    public static final Color whitesmoke = Color.createNamedColor("whitesmoke",0xf5f5f5);
    public static final Color yellow = Color.createNamedColor("yellow",0xffff00);
    public static final Color yellowgreen = Color.createNamedColor("yellowgreen",0x9acd32);
    //endregion

}
