package com.teamresourceful.resourcefulbees.common.config;

import com.teamresourceful.resourcefulconfig.common.annotations.*;
import com.teamresourceful.resourcefulconfig.common.config.EntryType;

@Category(id = "centrifuge", translation = "Centrifuge")
public final class CentrifugeConfig {

    @ConfigEntry(
        id = "globalCentrifugeRecipeTime",
        type = EntryType.INTEGER,
        translation = "Global Centrifuge Recipe Time"
    )
    @Comment(
        value = """
        Global recipe time for generated centrifuge recipes
        This does not affect recipes that are not auto generated by us.
        Time is in ticks.
        """
    )
    @IntRange(min = 100, max = 2400)
    public static int globalCentrifugeRecipeTime = 200;

    @ConfigEntry(
        id = "centrifugeRfPerTick",
        type = EntryType.INTEGER,
        translation = "Centrifuge RF Per Tick"
    )
    @Comment(
        value = "RF/t consumed by the centrifuge when processing recipes. Mutliblock Centrifuge cuts this value in half."
    )
    @IntRange(min = 2, max = 1000)
    public static int centrifugeRfPerTick = 30;

    @ConfigEntry(
            id = "recipeTimeExponent",
            type = EntryType.DOUBLE,
            translation = "Recipe Time Exponent"
    )
    @Comment(
            value = """
                    The recipe time modifier is calculated as:
                    numGearboxes^(1-x/numInputs)
                    Larger values for X means gearboxes have more impact on the time reduction.
                    """
    )
    @DoubleRange(min = 0, max = 1)
    public static double recipeTimeExponent = 0.1;

    @ConfigEntry(
            id = "gearboxPowerExponent",
            type = EntryType.DOUBLE,
            translation = "Gearbox Power Exponent"
    )
    @Comment(
            value = """
                    The gearbox power modifier is calculated as:
                    1 + (x * 1.1^numGearboxes)
                    Larger values for X means gearboxes have more impact on the power required to process a recipe.
                    The calculated modifier is multiplied by the processor power modifier before being applied to the recipe rf/t.
                    """
    )
    @DoubleRange(min = 0, max = 1)
    public static double gearboxPowerExponent = 0.2;

    @ConfigEntry(
            id = "cpuPowerExponent",
            type = EntryType.DOUBLE,
            translation = "Processor Power Exponent"
    )
    @Comment(
            value = """
                    The processor power modifier is calculated as:
                    1 + (x * 1.1^numProcessors)
                    Larger values for X means processors have more impact on the power required to process a recipe.
                    The calculated modifier is multiplied by the gearbox power modifier before being applied to the recipe rf/t.
                    """
    )
    @DoubleRange(min = 0, max = 1)
    public static double cpuPowerExponent = 0.4;

}
