package com.teamresourceful.resourcefulbees.common.config;

import com.teamresourceful.resourcefulconfig.common.annotations.*;
import com.teamresourceful.resourcefulconfig.common.config.EntryType;

@Category(id = "centrifuge", translation = "Centrifuge")
public final class CentrifugeConfig {

    @ConfigEntry(
        id = "globalCentrifugeRecipeTime",
        type = EntryType.INTEGER,
        translation = "Global Centrifuge Recipe Time"
    )
    @Comment(
        value = """
        Global recipe time for generated centrifuge recipes
        This does not affect recipes that are not auto generated by us.
        Time is in ticks.
        """
    )
    @IntRange(min = 100, max = 2400)
    public static int globalCentrifugeRecipeTime = 200;

    @ConfigEntry(
        id = "centrifugeRfPerTick",
        type = EntryType.INTEGER,
        translation = "Centrifuge RF Per Tick"
    )
    @Comment(
        value = "RF/t consumed by the centrifuge when processing recipes. Mutliblock Centrifuge cuts this value in half."
    )
    @IntRange(min = 2, max = 1000)
    public static int centrifugeRfPerTick = 30;



}
